#########################
## Toolchain variables ##
#########################

# Default toolchain directory
TOOLCHAIN_DIR=/opt/miyooflip-toolchain

# All toolchain-related variables may be
# overridden via the command line

CC              = $(TOOLCHAIN_DIR)/usr/bin/aarch64-linux-gcc
CXX             = $(TOOLCHAIN_DIR)/usr/bin/aarch64-linux-g++
STRIP           = $(TOOLCHAIN_DIR)/usr/bin/aarch64-linux-strip

SDL2_CONFIG     ?= $(TOOLCHAIN_DIR)/usr/aarch64-miyooflip-linux-gnu/sysroot/usr/bin/sdl2-config
FREETYPE_CONFIG ?= $(TOOLCHAIN_DIR)/usr/aarch64-miyooflip-linux-gnu/sysroot/usr/bin/freetype-config

INC_DIR         ?= $(TOOLCHAIN_DIR)/usr/aarch64-miyooflip-linux-gnu/sysroot/usr/include
LIB_DIR         ?= $(TOOLCHAIN_DIR)/usr/aarch64-miyooflip-linux-gnu/sysroot/usr/lib

#########################
#########################

PACKAGE_NAME = retroarch

DEBUG ?= 0

MIYOOFLIP=1
HAVE_SCREENSHOTS = 1
HAVE_REWIND = 1
HAVE_7ZIP = 1
HAVE_AL = 0
HAVE_ALSA = 1
HAVE_DSP_FILTER = 1
HAVE_VIDEO_FILTER = 1
HAVE_STATIC_VIDEO_FILTERS = 1
HAVE_STATIC_AUDIO_FILTERS = 1
HAVE_FILTERS_BUILTIN	= 1
HAVE_BUILTINMBEDTLS = 1
HAVE_BUILTINZLIB = 1
HAVE_C99 = 1
HAVE_CC = 1
HAVE_CC_RESAMPLER = 1
HAVE_CHD = 1
HAVE_COMMAND = 1
HAVE_CXX = 1
HAVE_DR_MP3 = 1
HAVE_DYNAMIC = 1
HAVE_EGL = 1
HAVE_FREETYPE = 1
HAVE_GDI = 1
HAVE_GETADDRINFO = 1
HAVE_GETOPT_LONG = 1
HAVE_GLSL = 1
HAVE_HID = 1
HAVE_IBXM = 1
HAVE_IFINFO = 1
HAVE_IMAGEVIEWER = 1
HAVE_LANGEXTRA = 1
HAVE_LIBRETRODB = 1
HAVE_MENU = 1
HAVE_MENU_COMMON = 1
HAVE_GFX_WIDGETS = 1
HAVE_MMAP = 1
HAVE_NETPLAYDISCOVERY = 1
HAVE_NETWORKING = 1
HAVE_ONLINE_UPDATER=1
HAVE_OPENDINGUX_FBDEV = 0
HAVE_OPENGL = 0
HAVE_OPENGL1 = 0
HAVE_OPENGLES = 1
HAVE_OPENGLES3 = 0
HAVE_MALI_FBDEV = 0
HAVE_OPENSSL = 1
HAVE_OVERLAY = 1
HAVE_RBMP = 1
HAVE_RJPEG = 1
HAVE_RPILED = 0
HAVE_RPNG = 1
HAVE_RUNAHEAD = 1
HAVE_SDL2 = 1
HAVE_SHADERPIPELINE = 1
HAVE_STB_FONT = 1
HAVE_STB_VORBIS = 1
HAVE_STB_IMAGE = 1
HAVE_STDIN_CMD = 0
HAVE_STRCASESTR = 1
HAVE_THREADS = 1
HAVE_UDEV = 1
HAVE_RGUI = 1
HAVE_MATERIALUI = 0
HAVE_XMB = 1
HAVE_OZONE = 1
HAVE_ZLIB = 1
HAVE_CONFIGFILE = 1
HAVE_PATCH = 1
HAVE_CHEATS = 1
HAVE_CHEEVOS = 1
HAVE_LIBSHAKE = 0
HAVE_CORE_INFO_CACHE = 1
HAVE_NEAREST_RESAMPLER = 1
HAVE_ODROIDGO2 = 1
HAVE_OSS = 1
HAVE_KMS = 1

OS = Linux
TARGET = retroarch.flip

OBJ :=
LINK := $(CXX)
DEF_FLAGS := -march=armv8.2-a -mtune=cortex-a55 -fPIE -mcpu=cortex-a55+crc+fp+simd -fomit-frame-pointer
DEF_FLAGS += -ffunction-sections -fdata-sections
DEF_FLAGS += -I. -Ideps -Ideps/stb -MMD
DEF_FLAGS += -Wall -Wno-unused-variable -flto
DEF_FLAGS += -std=gnu99 -D_GNU_SOURCE
LIBS := -ldl -lz -lrt -lcrypto -lssl -pthread -lrga -lmali -lmali_hook -ldrm -lasound -ludev -lSDL2 -lSDL2_image -lSDL2_ttf -lfreetype -lm
CFLAGS :=
CXXFLAGS := -fno-exceptions -fno-rtti -std=c++11 -D__STDC_CONSTANT_MACROS
ASFLAGS :=
LDFLAGS := -Wl,--gc-sections
INCLUDE_DIRS = -I$(INC_DIR)
LIBRARY_DIRS = -L$(LIB_DIR)
DEFINES := -DRARCH_INTERNAL -D_FILE_OFFSET_BITS=64 -UHAVE_STATIC_DUMMY
DEFINES += -DHAVE_C99=1 -DHAVE_CXX=1
DEFINES += -DHAVE_GETOPT_LONG=1 -DHAVE_STRCASESTR=1 -DHAVE_DYNAMIC=1 -DMIYOOFLIP
DEFINES += -DHAVE_FILTERS_BUILTIN -DHAVE_ALSA -DHAVE_OPENSSL -DHAVE_UDEV -DHAVE_OSS -DHAVE_SDL2 -DHAVE_OPENGLES -DMESA_EGL_NO_X11_HEADERS -DHAVE_ODROIDGO2 -DHAVE_GLSL -DHAVE_KMS
DEFINES += -DHAVE_ONLINE_UPDATER -DHAVE_UPDATE_CORES -DHAVE_UPDATE_CORE_INFO
DEFINES += -DHAVE_UPDATE_ASSETS

SDL2_CFLAGS := $(shell $(SDL2_CONFIG) --cflags)
SDL2_LIBS := $(shell $(SDL2_CONFIG) --libs)
FREETYPE_CFLAGS := $(shell $(FREETYPE_CONFIG) --cflags)
FREETYPE_LIBS := $(shell $(FREETYPE_CONFIG) --libs)
MMAP_LIBS = -lc

OBJDIR_BASE := obj-unix

ifeq ($(DEBUG), 1)
   OBJDIR := $(OBJDIR_BASE)/debug
   DEF_FLAGS += -O0 -g -DDEBUG -D_DEBUG
else
   OBJDIR := $(OBJDIR_BASE)/release
   DEF_FLAGS += -O2 -DNDEBUG
endif

include Makefile.common

DEF_FLAGS += $(INCLUDE_DIRS)
LDFLAGS += $(CFLAGS) $(CXXFLAGS) $(DEF_FLAGS)
CFLAGS += $(DEF_FLAGS)
CXXFLAGS += $(DEF_FLAGS)

HEADERS = $(wildcard */*/*.h) $(wildcard */*.h) $(wildcard *.h)

Q := @

RARCH_OBJ := $(addprefix $(OBJDIR)/,$(OBJ))

all: $(TARGET)

-include $(RARCH_OBJ:.o=.d)

SYMBOL_MAP := -Wl,-Map=output.map

$(TARGET): $(RARCH_OBJ)
	@$(if $(Q), $(shell echo echo LD $@),)
	$(Q)$(LINK) -o $@ $(RARCH_OBJ) $(LIBS) $(LDFLAGS) $(LIBRARY_DIRS)

ifeq ($(STRIP_BIN),1)
	$(STRIP) --strip-unneeded $(TARGET)
endif

$(OBJDIR)/%.o: %.c
	@mkdir -p $(dir $@)
	@$(if $(Q), $(shell echo echo CC $<),)
	$(Q)$(CC) $(CPPFLAGS) $(CFLAGS) $(DEFINES) -c -o $@ $<

$(OBJDIR)/%.o: %.cpp
	@mkdir -p $(dir $@)
	@$(if $(Q), $(shell echo echo CXX $<),)
	$(Q)$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(DEFINES) -MMD -c -o $@ $<

$(OBJDIR)/%.o: %.m
	@mkdir -p $(dir $@)
	@$(if $(Q), $(shell echo echo OBJC $<),)
	$(Q)$(CXX) $(OBJCFLAGS) $(DEFINES) -MMD -c -o $@ $<

$(OBJDIR)/%.o: %.S $(HEADERS)
	@mkdir -p $(dir $@)
	@$(if $(Q), $(shell echo echo AS $<),)
	$(Q)$(CC) $(CFLAGS) $(ASFLAGS) $(DEFINES) -c -o $@ $<

clean:
	rm -rf $(OBJDIR_BASE)
	rm -f $(TARGET)
	rm -f *.d

.PHONY: all clean

print-%:
	@echo '$*=$($*)'
